
services:
  
###> doctrine/doctrine-bundle ###
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8082:80"
    depends_on:
      - mysql
###< doctrine/doctrine-bundle ###

  mysql:
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  